server:
  port: 9999
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    name: miaosh
    url: jdbc:mysql://127.0.0.1:3306/miaosh
    username: root
    password: Dd112211
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 10
      jedis:
        pool:
          max-active: 50
          min-idle: 20



#使用druid数据源
#处理404等异常的方式
#配置springboot对redis的依赖

#设置jedis连接池

rocketmq:
  name-server: 120.27.151.16:9876
  producer:
    customized-trace-topic: stock

