package com.miaoshaoproject.dao;

import com.miaoshaoproject.dataobject.UserPwdDO;

public interface
UserPwdDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbggenerated Tue Apr 11 00:17:10 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbggenerated Tue Apr 11 00:17:10 CST 2023
     */
    int insert(UserPwdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbggenerated Tue Apr 11 00:17:10 CST 2023
     */
    int insertSelective(UserPwdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbggenerated Tue Apr 11 00:17:10 CST 2023
     */
    UserPwdDO selectByPrimaryKey(Integer id);
    UserPwdDO selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbggenerated Tue Apr 11 00:17:10 CST 2023
     */
    int updateByPrimaryKeySelective(UserPwdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbggenerated Tue Apr 11 00:17:10 CST 2023
     */
    int updateByPrimaryKey(UserPwdDO record);
}