server:
  port: 9999
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    name: miaosh
    url: jdbc:mysql://127.0.0.1:3306/miaosh
    username: root
    password: Dd112211
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#使用druid数据源
